### ISSUE TITLE
好像不能用呢？

### ISSUE THREAD

**Issue by hktalent** [1008pan/aitag#1]
<img width="1158" alt="image" src="https://user-images.githubusercontent.com/18223385/227941348-a520f7c1-bdf3-4aaa-b917-1e3da695942e.png">

**Comment by ZxwyWebSite** [comment]
可以用，不要直接打开html，会有CORS问题。需要部署到Nginx等Web服务器
演示地址：https://aitag.zxwy.ml/

还有你发的图片好像不是这个项目的吧，这个源是https://aitag.top/
而你的是https://github.com/WolfChen1996/NovelAI-tag-generator

**Comment by hktalent** [comment]
不是最新的https://aitag.top/吗？
<img width="1250" alt="image" src="https://user-images.githubusercontent.com/18223385/228269375-2186ea12-8577-403a-b549-59ea36c96f53.png">

**Comment by hktalent** [comment]
如果你能把所有图片也离线就更完美了
